# Generated by Django 4.2.11 on 2024-05-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('set_published_status', 'Can set published status')], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
