# Generated by Django 5.0.3 on 2024-03-27 15:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('address', models.CharField(max_length=250, verbose_name='адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'наш контакт',
                'verbose_name_plural': 'наши контакты',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(verbose_name='время редактирования'),
        ),
    ]
