# Generated by Django 5.0.3 on 2024-03-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_our_contact_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_contact',
            name='inn',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
    ]
