# Generated by Django 5.0.3 on 2024-04-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Our_contact',
            new_name='OurContact',
        ),
    ]
