# Generated by Django 4.2.11 on 2024-05-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', 'Может публиковать товар'), ('change_description', 'Может изменять описание товара'), ('change_category', 'Может изменять категорию товара')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
