# Generated by Django 4.2.11 on 2024-05-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', 'Can set published status'), ('change_description', 'Can change description'), ('change_category', 'Can change category')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
